name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

permissions:
  contents: read

env:
  SUPABASE_PROJECT_REF: wpvjuagjmpcvwglilzrb

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: supabase-deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (required by Supabase CLI)
        uses: actions/setup-node@v4
        with:
           node-version: '20'
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Show Supabase CLI version
        run: supabase --version

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy --project-ref "$SUPABASE_PROJECT_REF"
